stages: 
    - build
    - test
    - deploy

build website:
    image: node:16-alpine
    stage: build
    script:
      - yarn install
      - yarn build
    artifacts: 
      paths:
        - build

test websites:
    image: node:16-alpine
    stage: test
    script:
      - yarn global add serve
      - apk add curl
      - serve -s build &
      - sleep 10
      - curl http://localhost:3000 | grep "React App"

unit test:
    image: node:16-alpine
    stage: test
    script:
      - yarn install
      - yarn test


deploy to web:
    image: 
      name: google/cloud-sdk:452.0.1-alpine
      entrypoint: [""]
    script: 
      - gcloud --version
      - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT
      - gcloud config set project $GOOGLE_PROJECT_ID
      - gcloud storage buckets create gs://$GOOGLE_BUCKET --default-storage-class=STANDARD --uniform-bucket-level-access
      - gcloud storage rsync build gs://$GOOGLE_BUCKET
      - gcloud storage buckets add-iam-policy-binding  gs://$GOOGLE_BUCKET --member=allUsers --role=roles/storage.objectViewer
      - gcloud storage buckets update gs://$GOOGLE_BUCKET --web-main-page-suffix=index.html --web-error-page=index.html